
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'ScriptGoogleMaps': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue").default
  'ScriptGoogleMapsAdvancedMarkerElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue").default
  'ScriptGoogleMapsCircle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue").default
  'ScriptGoogleMapsHeatmapLayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue").default
  'ScriptGoogleMapsInfoWindow': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue").default
  'ScriptGoogleMapsMarker': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue").default
  'ScriptGoogleMapsMarkerClusterer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue").default
  'ScriptGoogleMapsPinElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue").default
  'ScriptGoogleMapsPolygon': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue").default
  'ScriptGoogleMapsPolyline': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue").default
  'ScriptGoogleMapsRectangle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue").default
  'ScriptAriaLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue").default
  'ScriptCarbonAds': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue").default
  'ScriptCrisp': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue").default
  'ScriptGoogleAdsense': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue").default
  'ScriptIntercom': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue").default
  'ScriptLemonSqueezy': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue").default
  'ScriptLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue").default
  'ScriptPayPalButtons': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue").default
  'ScriptPayPalMarks': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue").default
  'ScriptPayPalMessages': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue").default
  'ScriptStripePricingTable': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue").default
  'ScriptVimeoPlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue").default
  'ScriptYouTubePlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue").default
  'ProseA': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/A.vue").default
  'ProseAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Accordion.vue").default
  'ProseAccordionItem': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/AccordionItem.vue").default
  'ProseBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Badge.vue").default
  'ProseBlockquote': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Blockquote.vue").default
  'ProseCallout': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Callout.vue").default
  'ProseCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Card.vue").default
  'ProseCardGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CardGroup.vue").default
  'ProseCode': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Code.vue").default
  'ProseCodeCollapse': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeCollapse.vue").default
  'ProseCodeGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeGroup.vue").default
  'ProseCodeIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeIcon.vue").default
  'ProseCodePreview': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodePreview.vue").default
  'ProseCodeTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeTree.vue").default
  'ProseCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Collapsible.vue").default
  'ProseEm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Em.vue").default
  'ProseField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Field.vue").default
  'ProseFieldGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/FieldGroup.vue").default
  'ProseH1': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H1.vue").default
  'ProseH2': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H2.vue").default
  'ProseH3': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H3.vue").default
  'ProseH4': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H4.vue").default
  'ProseHr': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Hr.vue").default
  'ProseIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Icon.vue").default
  'ProseImg': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Img.vue").default
  'ProseKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Kbd.vue").default
  'ProseLi': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Li.vue").default
  'ProseOl': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Ol.vue").default
  'ProseP': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/P.vue").default
  'ProsePre': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Pre.vue").default
  'ProseScript': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Script.vue").default
  'ProseSteps': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Steps.vue").default
  'ProseStrong': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Strong.vue").default
  'ProseTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Table.vue").default
  'ProseTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tabs.vue").default
  'ProseTabsItem': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/TabsItem.vue").default
  'ProseTbody': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tbody.vue").default
  'ProseTd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Td.vue").default
  'ProseTh': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Th.vue").default
  'ProseThead': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Thead.vue").default
  'ProseTr': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tr.vue").default
  'ProseUl': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Ul.vue").default
  'ProseCaution': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Caution.vue").default
  'ProseNote': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Note.vue").default
  'ProseTip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Tip.vue").default
  'ProseWarning': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Warning.vue").default
  'UContentNavigation': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentNavigation.vue").default
  'UContentSearch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSearch.vue").default
  'UContentSearchButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSearchButton.vue").default
  'UContentSurround': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSurround.vue").default
  'UContentToc': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentToc.vue").default
  'UColorModeAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default
  'UColorModeButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default
  'UColorModeImage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default
  'UColorModeSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default
  'UColorModeSwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default
  'UAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default
  'UAlert': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default
  'UApp': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default
  'UAuthForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default
  'UAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default
  'UAvatarGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default
  'UBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default
  'UBanner': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default
  'UBlogPost': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default
  'UBlogPosts': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default
  'UBreadcrumb': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default
  'UButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default
  'UCalendar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default
  'UCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default
  'UCarousel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default
  'UChangelogVersion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default
  'UChangelogVersions': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default
  'UChatMessage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default
  'UChatMessages': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default
  'UChatPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default
  'UChatPrompt': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default
  'UChatPromptSubmit': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default
  'UCheckbox': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default
  'UCheckboxGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default
  'UChip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default
  'UCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default
  'UColorPicker': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default
  'UCommandPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default
  'UContainer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default
  'UContextMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default
  'UContextMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default
  'UDashboardGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default
  'UDashboardNavbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default
  'UDashboardPanel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default
  'UDashboardResizeHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default
  'UDashboardSearch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default
  'UDashboardSearchButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default
  'UDashboardSidebar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default
  'UDashboardSidebarCollapse': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default
  'UDashboardSidebarToggle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default
  'UDashboardToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default
  'UDrawer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default
  'UDropdownMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default
  'UDropdownMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default
  'UEditor': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default
  'UEditorDragHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default
  'UEditorEmojiMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default
  'UEditorMentionMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default
  'UEditorSuggestionMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default
  'UEditorToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default
  'UEmpty': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default
  'UError': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default
  'UFieldGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default
  'UFileUpload': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default
  'UFooter': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default
  'UFooterColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default
  'UForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default
  'UFormField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default
  'UHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default
  'UIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default
  'UInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default
  'UInputDate': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default
  'UInputMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default
  'UInputNumber': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default
  'UInputTags': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default
  'UInputTime': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default
  'UKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default
  'ULink': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default
  'ULinkBase': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default
  'UMain': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default
  'UMarquee': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default
  'UModal': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default
  'UNavigationMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default
  'UOverlayProvider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default
  'UPage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default
  'UPageAnchors': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default
  'UPageAside': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default
  'UPageBody': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default
  'UPageCTA': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default
  'UPageCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default
  'UPageColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default
  'UPageFeature': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default
  'UPageGrid': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default
  'UPageHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default
  'UPageHero': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default
  'UPageLinks': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default
  'UPageList': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default
  'UPageLogos': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default
  'UPageSection': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default
  'UPagination': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default
  'UPinInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default
  'UPopover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default
  'UPricingPlan': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default
  'UPricingPlans': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default
  'UPricingTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default
  'UProgress': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default
  'URadioGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default
  'UScrollArea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default
  'USelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default
  'USelectMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default
  'USeparator': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default
  'USkeleton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default
  'USlideover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default
  'USlider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default
  'UStepper': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default
  'USwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default
  'UTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default
  'UTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default
  'UTextarea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default
  'UTimeline': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default
  'UToast': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default
  'UToaster': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default
  'UTooltip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default
  'UTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default
  'UUser': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default
  'ULocaleSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default
  'ProseH5': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default
  'ProseH6': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
  'ContentRenderer': typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default
  'NuxtIsland': typeof import("../../node_modules/@nuxt/hints/dist/runtime/core/components/nuxt-island").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'MDC': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default
  'MDCCached': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue").default
  'MDCRenderer': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default
  'MDCSlot': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default
  'LazyScriptGoogleMaps': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue").default>
  'LazyScriptGoogleMapsAdvancedMarkerElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue").default>
  'LazyScriptGoogleMapsCircle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue").default>
  'LazyScriptGoogleMapsHeatmapLayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue").default>
  'LazyScriptGoogleMapsInfoWindow': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue").default>
  'LazyScriptGoogleMapsMarker': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue").default>
  'LazyScriptGoogleMapsMarkerClusterer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue").default>
  'LazyScriptGoogleMapsPinElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue").default>
  'LazyScriptGoogleMapsPolygon': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue").default>
  'LazyScriptGoogleMapsPolyline': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue").default>
  'LazyScriptGoogleMapsRectangle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue").default>
  'LazyScriptAriaLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue").default>
  'LazyScriptCarbonAds': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue").default>
  'LazyScriptCrisp': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue").default>
  'LazyScriptGoogleAdsense': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue").default>
  'LazyScriptIntercom': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue").default>
  'LazyScriptLemonSqueezy': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue").default>
  'LazyScriptLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue").default>
  'LazyScriptPayPalButtons': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue").default>
  'LazyScriptPayPalMarks': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue").default>
  'LazyScriptPayPalMessages': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue").default>
  'LazyScriptStripePricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue").default>
  'LazyScriptVimeoPlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue").default>
  'LazyScriptYouTubePlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue").default>
  'LazyProseA': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/A.vue").default>
  'LazyProseAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Accordion.vue").default>
  'LazyProseAccordionItem': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/AccordionItem.vue").default>
  'LazyProseBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Badge.vue").default>
  'LazyProseBlockquote': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Blockquote.vue").default>
  'LazyProseCallout': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Callout.vue").default>
  'LazyProseCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Card.vue").default>
  'LazyProseCardGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CardGroup.vue").default>
  'LazyProseCode': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Code.vue").default>
  'LazyProseCodeCollapse': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeCollapse.vue").default>
  'LazyProseCodeGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeGroup.vue").default>
  'LazyProseCodeIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeIcon.vue").default>
  'LazyProseCodePreview': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodePreview.vue").default>
  'LazyProseCodeTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/CodeTree.vue").default>
  'LazyProseCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Collapsible.vue").default>
  'LazyProseEm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Em.vue").default>
  'LazyProseField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Field.vue").default>
  'LazyProseFieldGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/FieldGroup.vue").default>
  'LazyProseH1': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H1.vue").default>
  'LazyProseH2': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H2.vue").default>
  'LazyProseH3': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H3.vue").default>
  'LazyProseH4': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/H4.vue").default>
  'LazyProseHr': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Hr.vue").default>
  'LazyProseIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Icon.vue").default>
  'LazyProseImg': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Img.vue").default>
  'LazyProseKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Kbd.vue").default>
  'LazyProseLi': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Li.vue").default>
  'LazyProseOl': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Ol.vue").default>
  'LazyProseP': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/P.vue").default>
  'LazyProsePre': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Pre.vue").default>
  'LazyProseScript': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Script.vue").default>
  'LazyProseSteps': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Steps.vue").default>
  'LazyProseStrong': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Strong.vue").default>
  'LazyProseTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Table.vue").default>
  'LazyProseTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tabs.vue").default>
  'LazyProseTabsItem': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/TabsItem.vue").default>
  'LazyProseTbody': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tbody.vue").default>
  'LazyProseTd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Td.vue").default>
  'LazyProseTh': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Th.vue").default>
  'LazyProseThead': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Thead.vue").default>
  'LazyProseTr': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Tr.vue").default>
  'LazyProseUl': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/Ul.vue").default>
  'LazyProseCaution': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Caution.vue").default>
  'LazyProseNote': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Note.vue").default>
  'LazyProseTip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Tip.vue").default>
  'LazyProseWarning': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/prose/callout/Warning.vue").default>
  'LazyUContentNavigation': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentNavigation.vue").default>
  'LazyUContentSearch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSearch.vue").default>
  'LazyUContentSearchButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSearchButton.vue").default>
  'LazyUContentSurround': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentSurround.vue").default>
  'LazyUContentToc': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/content/ContentToc.vue").default>
  'LazyUColorModeAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default>
  'LazyUColorModeButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default>
  'LazyUColorModeImage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default>
  'LazyUColorModeSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default>
  'LazyUColorModeSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default>
  'LazyUAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default>
  'LazyUAlert': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default>
  'LazyUApp': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default>
  'LazyUAuthForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default>
  'LazyUAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default>
  'LazyUAvatarGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default>
  'LazyUBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default>
  'LazyUBanner': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default>
  'LazyUBlogPost': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default>
  'LazyUBlogPosts': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default>
  'LazyUBreadcrumb': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default>
  'LazyUButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default>
  'LazyUCalendar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default>
  'LazyUCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default>
  'LazyUCarousel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default>
  'LazyUChangelogVersion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default>
  'LazyUChangelogVersions': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default>
  'LazyUChatMessage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default>
  'LazyUChatMessages': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default>
  'LazyUChatPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default>
  'LazyUChatPrompt': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default>
  'LazyUChatPromptSubmit': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default>
  'LazyUCheckbox': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default>
  'LazyUCheckboxGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default>
  'LazyUChip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default>
  'LazyUCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default>
  'LazyUColorPicker': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default>
  'LazyUCommandPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default>
  'LazyUContainer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default>
  'LazyUContextMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default>
  'LazyUContextMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default>
  'LazyUDashboardGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default>
  'LazyUDashboardNavbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default>
  'LazyUDashboardPanel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default>
  'LazyUDashboardResizeHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default>
  'LazyUDashboardSearch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default>
  'LazyUDashboardSearchButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default>
  'LazyUDashboardSidebar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default>
  'LazyUDashboardSidebarCollapse': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default>
  'LazyUDashboardSidebarToggle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default>
  'LazyUDashboardToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default>
  'LazyUDrawer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default>
  'LazyUDropdownMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default>
  'LazyUDropdownMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default>
  'LazyUEditor': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default>
  'LazyUEditorDragHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default>
  'LazyUEditorEmojiMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default>
  'LazyUEditorMentionMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default>
  'LazyUEditorSuggestionMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default>
  'LazyUEditorToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default>
  'LazyUEmpty': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default>
  'LazyUError': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default>
  'LazyUFieldGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default>
  'LazyUFileUpload': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default>
  'LazyUFooter': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default>
  'LazyUFooterColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default>
  'LazyUForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default>
  'LazyUFormField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default>
  'LazyUHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default>
  'LazyUIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default>
  'LazyUInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default>
  'LazyUInputDate': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default>
  'LazyUInputMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default>
  'LazyUInputNumber': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default>
  'LazyUInputTags': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default>
  'LazyUInputTime': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default>
  'LazyUKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default>
  'LazyULink': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default>
  'LazyULinkBase': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default>
  'LazyUMain': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default>
  'LazyUMarquee': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default>
  'LazyUModal': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default>
  'LazyUNavigationMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default>
  'LazyUOverlayProvider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default>
  'LazyUPage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default>
  'LazyUPageAnchors': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default>
  'LazyUPageAside': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default>
  'LazyUPageBody': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default>
  'LazyUPageCTA': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default>
  'LazyUPageCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default>
  'LazyUPageColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default>
  'LazyUPageFeature': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default>
  'LazyUPageGrid': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default>
  'LazyUPageHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default>
  'LazyUPageHero': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default>
  'LazyUPageLinks': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default>
  'LazyUPageList': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default>
  'LazyUPageLogos': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default>
  'LazyUPageSection': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default>
  'LazyUPagination': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default>
  'LazyUPinInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default>
  'LazyUPopover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default>
  'LazyUPricingPlan': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default>
  'LazyUPricingPlans': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default>
  'LazyUPricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default>
  'LazyUProgress': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default>
  'LazyURadioGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default>
  'LazyUScrollArea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default>
  'LazyUSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default>
  'LazyUSelectMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default>
  'LazyUSeparator': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default>
  'LazyUSkeleton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default>
  'LazyUSlideover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default>
  'LazyUSlider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default>
  'LazyUStepper': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default>
  'LazyUSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default>
  'LazyUTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default>
  'LazyUTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default>
  'LazyUTextarea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default>
  'LazyUTimeline': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default>
  'LazyUToast': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default>
  'LazyUToaster': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default>
  'LazyUTooltip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default>
  'LazyUTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default>
  'LazyUUser': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default>
  'LazyULocaleSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default>
  'LazyProseH5': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default>
  'LazyProseH6': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
  'LazyContentRenderer': LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/@nuxt/hints/dist/runtime/core/components/nuxt-island").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyMDC': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default>
  'LazyMDCCached': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue").default>
  'LazyMDCRenderer': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default>
  'LazyMDCSlot': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
